<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common.Utils\Common.Utils.csproj" />
      <ProjectReference Include="..\Database.Users\Database.Users.csproj" />
    </ItemGroup>

</Project>
