AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Application to manage Linkin Park Concert dates

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: dotnet8
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'POST, GET, PUT, DELETE'"
      AllowOrigin: "'*'"
      AllowHeaders: "'*'"
      #MaxAge: "'600'"


Parameters:
  CallbackUrl:
    Type: String
  UserPoolId:
    Type: String
      
Resources:
  # Database
  ConcertsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}_Concerts
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        #- AttributeName: PostedStartTime
        #  AttributeType: S
        #- AttributeName: Country
        #  AttributeType: S
        #- AttributeName: State
        #  AttributeType: S
        #- AttributeName: City
        #  AttributeType: S
        #- AttributeName: Venue
        #  AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  
  # Access Roles
  ConcertsWriteLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaDynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:DescribeTable
                Resource: !GetAtt ConcertsDynamoDBTable.Arn
  ConcertsReadLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaDynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:DescribeTable
                  - dynamodb:Scan
                Resource: !GetAtt ConcertsDynamoDBTable.Arn
  
  CognitoAuthorizerUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${UserPoolId}-userpool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 7
      AutoVerifiedAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: true
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Mutable: true
          Name: email
          #Required: true
        - AttributeDataType: String
          Mutable: true
          Name: first_name
          #Required: true
        - AttributeDataType: String
          Mutable: true
          Name: last_name
          #Required: true
  
  CognitoAuthorizerUserPoolResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      Identifier: !Sub ${AWS::StackName}_LpConcertsAuthServer
      Name: !Sub ${AWS::StackName}_LpConcertsAuthServer
      Scopes:
        - ScopeDescription: "Allow access to application"
          ScopeName: user_access
      UserPoolId: !Ref CognitoAuthorizerUserPool
  
  CognitoAuthorizerUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AllowedOAuthFlows:
        - implicit
        - code
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - !Sub ${AWS::StackName}_LpConcertsAuthServer/user_access
      CallbackURLs:
        - !Ref CallbackUrl
        - http://localhost:4200
        - http://localhost:4200/
        - http://localhost:4200/home
      LogoutURLs:
        - !Ref CallbackUrl
      ClientName: !Sub ${UserPoolId}-client
      SupportedIdentityProviders:
        - COGNITO
      UserPoolId: !Ref CognitoAuthorizerUserPool
      GenerateSecret: false
  
  CognitoAuthorizerUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ${AWS::StackName}-${AWS::AccountId}
      UserPoolId: !Ref CognitoAuthorizerUserPool
  
  # REST API that is secured by cognito
  ConcertsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'POST, GET, PUT, DELETE'"
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
      Auth:
        Authorizers:
          ConcertsCognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoAuthorizerUserPool.Arn
            IdentitySource: method.request.header.Authorization
            Scopes:
              - !Sub ${AWS::StackName}_LpConcertsAuthServer/user_access
  
  # CORS Cloudfront
  CORSOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub ${AWS::StackName}_CORSOriginRequestPolicy
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - Origin
            - Access-Control-Request-Headers
            - Access-Control-Request-Method
        QueryStringsConfig:
          QueryStringBehavior: all
        CookiesConfig:
          CookieBehavior: none
  
  CORSResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub ${AWS::StackName}_CORSResponseHeadersPolicy
        Comment: "Add CORS headers to the response"
        CorsConfig:
          AccessControlAllowCredentials: false
          AccessControlAllowHeaders:
            Items:
              - '*'
          AccessControlAllowMethods:
            Items:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
          AccessControlAllowOrigins:
            Items:
              - '*'
          AccessControlExposeHeaders:
            Items:
              - '*'
          OriginOverride: true
        SecurityHeadersConfig:
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: SAMEORIGIN
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: no-referrer
            Override: true
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Override: true
  
  # Cloudfront caching
  DefaultCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub ${AWS::StackName}_DefaultCachePolicy
        DefaultTTL: 3600
        MaxTTL: 86400
        MinTTL: 60
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: all
          EnableAcceptEncodingBrotli: false
          EnableAcceptEncodingGzip: false
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Authorization
          QueryStringsConfig:
            QueryStringBehavior: all
  
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: ApiGatewayOrigin
            DomainName: !Sub "${ConcertsApi}.execute-api.${AWS::Region}.amazonaws.com"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        DefaultCacheBehavior:
          TargetOriginId: ApiGatewayOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachePolicyId: !Ref DefaultCachePolicy
          OriginRequestPolicyId: !Ref CORSOriginRequestPolicy
          ResponseHeadersPolicyId: !Ref CORSResponseHeadersPolicy
        Enabled: true
        Comment: "LP Concerts CloudFront Distribution"
        PriceClass: PriceClass_100
  
  
  # Lambda functions
  AddConcertFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Lambda.AddConcert::Lambda.AddConcert.Function::FunctionHandler
      Role: !GetAtt ConcertsWriteLambdaExecutionRole.Arn
      Description: .NET function to add calendar entries
      CodeUri: ./Lambda.AddConcert/src/Lambda.AddConcert/bin/Release/net8.0/Lambda.AddConcert.zip
      Architectures:
        - arm64
      Tracing: Active
      Environment:
        Variables:
          CONCERTS_TABLE_NAME: !Ref ConcertsDynamoDBTable
      Events:
        PutAddConcert:
          Type: Api
          Properties:
            RestApiId: !Ref ConcertsApi
            Path: /addConcert
            Method: put
            Auth:
              Authorizer: ConcertsCognitoAuthorizer
              AuthorizationScopes:
                - openid
                #- !Sub ${AWS::StackName}_LpConcertsAuthServer/user_access
  
  DeleteConcertFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Lambda.DeleteConcert::Lambda.DeleteConcert.Function::FunctionHandler
      Role: !GetAtt ConcertsWriteLambdaExecutionRole.Arn
      Description: .NET function to remove calendar entries
      CodeUri: ./Lambda.DeleteConcert/src/Lambda.DeleteConcert/bin/Release/net8.0/Lambda.DeleteConcert.zip
      Architectures:
        - arm64
      Tracing: Active
      Environment:
        Variables:
          CONCERTS_TABLE_NAME: !Ref ConcertsDynamoDBTable
      Events:
        PutAddConcert:
          Type: Api
          Properties:
            RestApiId: !Ref ConcertsApi
            Path: /deleteConcert/{concertId}
            Method: delete
            Auth:
              Authorizer: ConcertsCognitoAuthorizer
              AuthorizationScopes:
                - openid
                #- !Sub ${AWS::StackName}_LpConcertsAuthServer/user_access
  
  FindConcertFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Lambda.ListConcerts::Lambda.ListConcerts.Function::FunctionHandler
      Role: !GetAtt ConcertsReadLambdaExecutionRole.Arn
      Description: .NET function to read calendar entries
      CodeUri: ./Lambda.ListConcerts/src/Lambda.ListConcerts/bin/Release/net8.0/Lambda.ListConcerts.zip
      Architectures:
        - arm64
      Tracing: Active
      Environment:
        Variables:
          CONCERTS_TABLE_NAME: !Ref ConcertsDynamoDBTable
      Events:
        ListConcerts:
          Type: Api
          Properties:
            RestApiId: !Ref ConcertsApi
            Path: /concerts
            Method: get
  
  ConcertCalendarFeedFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Lambda.CalendarFeed::Lambda.CalendarFeed.Function::FunctionHandler
      Role: !GetAtt ConcertsReadLambdaExecutionRole.Arn
      Description: .NET function to read calendar entries as iCal to create a feed
      CodeUri: ./Lambda.CalendarFeed/src/Lambda.CalendarFeed/bin/Release/net8.0/Lambda.CalendarFeed.zip
      Architectures:
        - arm64
      Tracing: Active
      Environment:
        Variables:
          CONCERTS_TABLE_NAME: !Ref ConcertsDynamoDBTable
      Events:
        ListConcerts: # TODO: maybe rename?
          Type: Api
          Properties:
            RestApiId: !Ref ConcertsApi
            Path: /feed/ical
            Method: get


Outputs:
  HostedUi:
    Description: Hosted UI
    Value: !Sub "https://${CognitoAuthorizerUserPoolDomain}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${CognitoAuthorizerUserPoolClient}&response_type=token&scope=email+openid+profile&redirect_uri=${CallbackUrl}"

  UserPoolId:
    Description: "UserPool ID"
    Value: !Ref CognitoAuthorizerUserPool
    #Export:
    #  Name: !Sub "${UserPoolId}UserPoolId"

  UserPoolClientId:
    Description: "UserPoolClient ID"
    Value: !Ref CognitoAuthorizerUserPoolClient
    #Export:
    #  Name: !Sub "${UserPoolId}UserPoolClientId"

  #UserPoolClientIdSecret:
  #  Value:
  #    !GetAtt CognitoAuthorizerUserPoolClient.ClientSecret
  
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  #GetCalendar:
  #  Description: "Function to read the calendar"
  #  Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getCalendar/"
  #AddConcertFunction:
  #  Description: "Hello World Lambda Function ARN"
  #  Value: !GetAtt AddConcertFunction.Arn
  #AddConcertFunctionRole:
  #  Description: "Implicit IAM Role created for Hello World function"
  #  Value: !GetAtt AddConcertFunctionRole.Arn
