// <auto-generated />
using System;
using Database.Tours;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Tours.Migrations
{
    [DbContext(typeof(ToursDbContext))]
    partial class ToursDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Database.Tours.DataObjects.CityDo", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CountryCode");

                    b.Property<string>("StateCode")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("StateCode");

                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("Name");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("NativeName");

                    b.HasKey("CountryCode", "StateCode", "Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.ConcertDo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("Id");

                    b.Property<uint>("ConcertTypeId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("ConcertTypeId");

                    b.Property<string>("CustomTitle")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("CustomTitle");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("DeletedAt");

                    b.Property<DateTime?>("DoorsTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DoorsTime");

                    b.Property<uint>("ExpectedSetDurationMinutes")
                        .HasColumnType("int unsigned")
                        .HasColumnName("ExpectedSetDurationMinutes");

                    b.Property<bool>("LpuEarlyEntryConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("LpuEarlyEntryConfirmed");

                    b.Property<DateTime?>("LpuEarlyEntryTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LpuEarlyEntryTime");

                    b.Property<DateTime?>("MainStageTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("MainStageTime");

                    b.Property<DateTimeOffset>("PostedStartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("PostedStartTime");

                    b.Property<string>("ScheduleImageFile")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("ScheduleImageFile");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("TourId")
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)")
                        .HasColumnName("TourId");

                    b.Property<string>("TourLegId")
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)")
                        .HasColumnName("TourLegId");

                    b.Property<uint>("VenueId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("VenueId");

                    b.HasKey("Id");

                    b.HasIndex("ConcertTypeId");

                    b.HasIndex("TourId");

                    b.HasIndex("TourLegId");

                    b.HasIndex("VenueId");

                    b.ToTable("Concert");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.ConcertTypeDo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ConcertType");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.CountryDo", b =>
                {
                    b.Property<string>("IsoCode")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("IsoCode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("Name");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("NativeName");

                    b.HasKey("IsoCode");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.PreviousVenueNameDo", b =>
                {
                    b.Property<uint>("VenueId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("VenueId");

                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned")
                        .HasColumnName("Id");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date")
                        .HasColumnName("From");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("Name");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date")
                        .HasColumnName("To");

                    b.HasKey("VenueId", "Id");

                    b.ToTable("PreviousVenueName");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.StateDo", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CountryCode");

                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("Name");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("NativeName");

                    b.HasKey("CountryCode", "Code");

                    b.ToTable("State");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.TourDo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Tour");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.TourLegDo", b =>
                {
                    b.Property<string>("TourId")
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)")
                        .HasColumnName("TourId");

                    b.Property<string>("Id")
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("Name");

                    b.HasKey("TourId", "Id");

                    b.ToTable("TourLeg");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.VenueDo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("CityId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("CityId");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CountryCode");

                    b.Property<string>("CurrentName")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("CurrentName");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Longitude");

                    b.Property<string>("StateCode")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("StateCode");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)")
                        .HasColumnName("TimeZone");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "StateCode", "CityId");

                    b.ToTable("Venue");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.CityDo", b =>
                {
                    b.HasOne("Database.Tours.DataObjects.CountryDo", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Tours.DataObjects.StateDo", "State")
                        .WithMany()
                        .HasForeignKey("CountryCode", "StateCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.ConcertDo", b =>
                {
                    b.HasOne("Database.Tours.DataObjects.ConcertTypeDo", "Type")
                        .WithMany()
                        .HasForeignKey("ConcertTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Tours.DataObjects.TourDo", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId");

                    b.HasOne("Database.Tours.DataObjects.TourLegDo", "TourLeg")
                        .WithMany()
                        .HasForeignKey("TourLegId")
                        .HasPrincipalKey("Id");

                    b.HasOne("Database.Tours.DataObjects.VenueDo", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("TourLeg");

                    b.Navigation("Type");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.PreviousVenueNameDo", b =>
                {
                    b.HasOne("Database.Tours.DataObjects.VenueDo", "Venue")
                        .WithMany("PreviousNames")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.StateDo", b =>
                {
                    b.HasOne("Database.Tours.DataObjects.CountryDo", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.TourLegDo", b =>
                {
                    b.HasOne("Database.Tours.DataObjects.TourDo", "Tour")
                        .WithMany("Legs")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.VenueDo", b =>
                {
                    b.HasOne("Database.Tours.DataObjects.CountryDo", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode");

                    b.HasOne("Database.Tours.DataObjects.StateDo", "State")
                        .WithMany()
                        .HasForeignKey("CountryCode", "StateCode");

                    b.HasOne("Database.Tours.DataObjects.CityDo", "City")
                        .WithMany()
                        .HasForeignKey("CountryCode", "StateCode", "CityId");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.TourDo", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("Database.Tours.DataObjects.VenueDo", b =>
                {
                    b.Navigation("PreviousNames");
                });
#pragma warning restore 612, 618
        }
    }
}
