AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Application to manage the domains for the LP Calendar project



Parameters:
  BaseProductName:
    Description: Name of the product. Is used as prefix in the exports
    Type: String
  RootDomain:
    Type: String
  HostedZoneId:
    Type: String
    Default: ""



Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${BaseProductName}-api-${AWS::Region}
      EndpointConfiguration:
        Types:
          - "REGIONAL"
