AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Description: >
  Application to manage the S3 Multi-Region access point for the frontend buckets


Parameters:
  BaseProductName:
    Description: Name of the product. Is used as prefix in the exports
    Type: String
  FrontendBucketRegions:
    Description: "Comma-delimited list of all regions that have a copy of the frontend bucket"
    Type: CommaDelimitedList


Resources:
  MultiRegionAccessPoint:
    Type: AWS::S3::MultiRegionAccessPoint
    Properties:
      Name: !Sub ${BaseProductName}-web-frontend-mrap
      Regions:
        - Bucket: !Join
            - '-'
            - - !Sub ${BaseProductName}-web-frontend-bucket
              - !Select [0, !Ref FrontendBucketRegions]
        - Bucket: !Join
            - '-'
            - - !Sub ${BaseProductName}-web-frontend-bucket
              - !Select [1, !Ref FrontendBucketRegions]


Outputs:
  FrontendMultiRegionAccessPoint:
    Description: 'S3 MRAP Bucket for the frontend files'
    Value: !Ref MultiRegionAccessPoint
    Export:
      Name: !Sub '${BaseProductName}-frontend-s3-mrap'
