AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Application to manage the domains for the LP Calendar project



Parameters:
  BaseProductName:
    Description: Name of the product. Is used as prefix in the exports
    Type: String
  RootDomain:
    Type: String
  HostedZoneId:
    Type: String
    Default: ""



Resources:
  # DNS entries if the zone is hosted in Route53
  AppDnsRecordSetGroup:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Sub 'api.${RootDomain}.'
          TTL: 600
          Type: CNAME
          AliasTarget:
            HostedZoneId: !Ref HostedZoneId
            DNSName: {'Fn::ImportValue': !Sub '${BaseProductName}-main-api-gateway-domain' }
