AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Application to manage the CloudFront deployment for the LP Calendar project



Parameters:
  BaseProductName:
    Description: Name of the product. Is used as prefix in the exports
    Type: String
  FrontendMultiRegionAccessPointAlias:
    Description: Alias of the MRAP for the frontend S3 buckets
    Type: String



Resources:
  # Lambda@Edge for redirects
  RedirectLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
                - 'edgelambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
  
  RedirectLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${BaseProductName}-redirect-lambda
      Handler: index.handler
      Role: !GetAtt RedirectLambdaFunctionRole.Arn
      Runtime: nodejs22.x
      AutoPublishAlias: live
      InlineCode: |
        exports.handler = async (event, context, callback) => {
          const request = event.Records[0].cf.request;
          const uri = request.uri;
          const querystring = request.querystring;
      
          // Check if path starts with /Prod/
          if (uri.startsWith('/Prod/')) {
            const newUri = uri.replace(/^\/Prod\//, '/v2/');
            const newUriWithQuery = newUri + (querystring ? `?${querystring}` : '');
            
            const response = {
              status: '301',
              statusDescription: 'Moved Permanently',
              headers: {
                location: [{
                  key: 'Location',
                  value: newUriWithQuery,
                }],
              },
            };
            
            return callback(null, response);
          }
      
          // Check if path starts with /latest/
          if (uri.startsWith('/latest/')) {
            const newUri = uri.replace(/^\/latest\//, '/v2/');
            const newUriWithQuery = newUri + (querystring ? `?${querystring}` : '');
            
            const response = {
              status: '302',
              statusDescription: 'Found v2',
              headers: {
                location: [{
                  key: 'Location',
                  value: newUriWithQuery,
                }],
              },
            };
            
            return callback(null, response);
          }
      
          // Otherwise, continue as normal
          return callback(null, request);
        };

  SignS3MrapLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: PublishVersion
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: !Sub 'arn:aws:s3::${AWS::AccountId}:accesspoint/${FrontendMultiRegionAccessPointAlias}/*'

  SignS3MrapLambdaFunctionNew:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${BaseProductName}-sign-s3-mrap-requests-new
      Handler: index.handler
      Role: !GetAtt SignS3MrapLambdaRole.Arn
      Runtime: nodejs22.x
      AutoPublishAlias: live
      # based on this code: https://gist.github.com/jbg/781792a2ecf2068c24c5ec7cf971a8e4
      InlineCode: |
        'use strict';
        
        const {
          CrtSignerV4,
        } = require('@aws-sdk/signature-v4-crt');
        
        const allowedHeaders = [
          "accept-encoding",
          "content-length",
          "if-modified-since",
          "if-none-match",
          "if-range",
          "if-unmodified-since",
          "transfer-encoding",
          "via",
        ];
        
        const signer = new CrtSignerV4({
          credentials: {
            accessKeyId: process.env["AWS_ACCESS_KEY_ID"],
            secretAccessKey: process.env["AWS_SECRET_ACCESS_KEY"],
            sessionToken: process.env["AWS_SESSION_TOKEN"],
          },
          region: "*",
          service: "s3",
          signingAlgorithm: 1,  // SigV4Asymmetric
        });
        
        exports.handler = async (event) => {
          const request = event.Records[0].cf.request;
          const originHostname = request.origin.custom.domainName;
        
          // Allow failover: if the origin is not a MRAP, skip SigV4A signing.
          if (!originHostname.endsWith(".mrap.accesspoint.s3-global.amazonaws.com")) {
            return request;
          }
        
          // X-Amz-Cf-Id will be added to the origin request after this function finishes.
          // Therefore, we have to include it in the signature in order for the signature
          // to verify successfully at the origin. However, we have to remove it from the
          // headers we return below, as we're not allowed to set this header.
          const cfRequestId = event.Records[0].cf.config.requestId;
        
          const headersToSign = {
            "Host": originHostname,
            "X-Amz-Cf-Id": cfRequestId,
          };
        
          for (const key of allowedHeaders) {
            if (key in request.headers) {
              const header = request.headers[key][0];
              headersToSign[header.key] = header.value;
            }
          }
        
          const signedRequest = await signer.sign({
            method: request.method,
            protocol: "https",
            hostname: originHostname,
            path: request.uri,
            headers: headersToSign,
          });
        
          const signedHeaders = {};
          for (const [key, value] of Object.entries(signedRequest.headers)) {
            if (key != "X-Amz-Cf-Id") {
              signedHeaders[key.toLowerCase()] = [{key, value}];
            }
          }
          request.headers = signedHeaders;
        
          // We ignore the query string. If you choose to pass it through, add it to
          // the signer.sign() call above.
          delete request.querystring;
        
          return request;
        };
  
  SignS3MrapLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${BaseProductName}-sign-s3-mrap-requests
      Handler: index.handler
      Role: !GetAtt SignS3MrapLambdaRole.Arn
      Runtime: nodejs22.x
      AutoPublishAlias: live
      InlineCode: |
        'use strict';
        
        const {
          CrtSignerV4,
        } = require('@aws-sdk/signature-v4-crt');
        
        const { HttpRequest } = require('@aws-sdk/protocol-http');
        const { defaultProvider } = require('@aws-sdk/credential-provider-node');
        
        const signer = new CrtSignerV4({
          service: 's3',
          region: '*',
          credentials: defaultProvider(),
        });
        
        function setHeader(headers, key, value) {
          console.info("Try set header", key, value);
          if (!value) return;
          headers[key.toLowerCase()] = [{
            key,
            value: String(value),
          }];
        }
        
        exports.handler = async (event) => {
          const request = event.Records[0].cf.request;
        
          console.info(JSON.stringify(request, null, 2));
          const endpoint = request.origin.custom.domainName;
        
          const httpRequest = new HttpRequest({
            protocol: 'https:',
            hostname: endpoint,
            method: request.method,
            path: request.uri,
            headers: {
              host: endpoint,
            },
          });
          httpRequest.headers['X-Amz-Region-Set'] = "*";
          
          console.info("httpRequest:", JSON.stringify(httpRequest, null, 2));
        
          const signed = await signer.sign(httpRequest);
        
          console.info("Signed request:", JSON.stringify(signed, null, 2));
        
          setHeader(request.headers, 'Authorization', signed.headers?.['Authorization']);
          setHeader(request.headers, 'X-Amz-Date', signed.headers?.['X-Amz-Date']);
          setHeader(request.headers, 'x-amz-content-sha256', signed.headers?.['x-amz-content-sha256']);
          
          request.headers.host = [{
            key: 'Host',
            value: endpoint,
          }];
        
          console.info("result: ", JSON.stringify(request, null, 2));
          return request;
        };


Outputs:
  RedirectLambdaFunctionArnExport:
    Description: 'Lambda@Edge function Version'
    Value: !Ref RedirectLambdaFunction.Version
    Export:
      Name: !Sub '${BaseProductName}-redirect-lambda-version'
  SignS3MrapLambdaFunctionArnExport:
    Description: 'Sign S3 MRAP Lambda@Edge function Version'
    Value: !Ref SignS3MrapLambdaFunctionNew.Version
    Export:
      Name: !Sub '${BaseProductName}-sign-s3-mrap-lambda-version'
