// <auto-generated />
using System;
using Database.Setlists;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Setlists.Migrations
{
    [DbContext(typeof(SetlistsDbContext))]
    [Migration("20260419093328_AddPremiereNotificationSent")]
    partial class AddPremiereNotificationSent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Database.Setlists.DataObjects.AlbumDo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("Id");

                    b.Property<string>("LinkinpediaUrl")
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("LinkinpediaUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SetlistActDo", b =>
                {
                    b.Property<uint>("SetlistId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("SetlistId");

                    b.Property<uint>("ActNumber")
                        .HasColumnType("int unsigned")
                        .HasColumnName("ActNumber");

                    b.Property<string>("Title")
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)")
                        .HasColumnName("Title");

                    b.HasKey("SetlistId", "ActNumber");

                    b.ToTable("SetlistAct");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SetlistDo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("Id");

                    b.Property<DateTime>("ConcertDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ConcertDate");

                    b.Property<string>("ConcertId")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("ConcertId");

                    b.Property<string>("ConcertTitle")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("ConcertTitle");

                    b.Property<string>("ConcertTourName")
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("ConcertTourName");

                    b.Property<string>("ConcertType")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("ConcertType");

                    b.Property<string>("LinkinpediaUrl")
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("LinkinpediaUrl");

                    b.Property<string>("SetName")
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("SetName");

                    b.HasKey("Id");

                    b.ToTable("Setlist");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SetlistEntryDo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Id");

                    b.Property<uint?>("ActNumber")
                        .HasColumnType("int unsigned")
                        .HasColumnName("ActNumber");

                    b.Property<string>("ExtraNotes")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("ExtraNotes");

                    b.Property<bool>("IsLivePremiere")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsLivePremiere");

                    b.Property<bool>("IsPlayedFromRecording")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsPlayedFromRecording");

                    b.Property<bool>("IsRotationSong")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsRotationSong");

                    b.Property<bool>("IsWorldPremiere")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsWorldPremiere");

                    b.Property<uint?>("PlayedMashupId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("PlayedMashupId");

                    b.Property<uint?>("PlayedSongId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("PlayedSongId");

                    b.Property<uint?>("PlayedSongVariantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("PlayedSongVariantId");

                    b.Property<bool>("PremiereNotificationSent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("PremiereNotificationSent");

                    b.Property<uint>("SetlistId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("SetlistId");

                    b.Property<ushort>("SongNumber")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("SongNumber");

                    b.Property<uint>("SortNumber")
                        .HasColumnType("int unsigned")
                        .HasColumnName("SortNumber");

                    b.Property<string>("TitleOverride")
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)")
                        .HasColumnName("TitleOverride");

                    b.HasKey("Id");

                    b.HasIndex("PlayedMashupId");

                    b.HasIndex("PlayedSongId");

                    b.HasIndex("PlayedSongVariantId");

                    b.HasIndex("SetlistId", "ActNumber");

                    b.ToTable("SetlistEntry");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SetlistEntrySongExtraDo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("Description");

                    b.Property<string>("SetlistEntryId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("SetlistEntryId");

                    b.Property<uint?>("SongId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("SongId");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetlistEntryId");

                    b.HasIndex("SongId");

                    b.ToTable("SetlistEntrySongExtra");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SongDo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("Id");

                    b.Property<uint?>("AlbumId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("AlbumId");

                    b.Property<string>("AppleMusicId")
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)")
                        .HasColumnName("appleMusicId");

                    b.Property<string>("Isrc")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Isrc");

                    b.Property<string>("LinkinpediaUrl")
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("LinkinpediaUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Song");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SongInMashupDo", b =>
                {
                    b.Property<uint>("MashupId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("MashupId");

                    b.Property<uint>("SongId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("SongId");

                    b.HasKey("MashupId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("SongInMashup", (string)null);
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SongMashupDo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("Id");

                    b.Property<string>("LinkinpediaUrl")
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("LinkinpediaUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("SongMashup");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SongVariantDo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("Id");

                    b.Property<string>("AppleMusicIdOverride")
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)")
                        .HasColumnName("appleMusicIdOverride");

                    b.Property<string>("Description")
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("Description");

                    b.Property<string>("IsrcOverride")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("IsrcOverride");

                    b.Property<uint>("SongId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("SongId");

                    b.Property<string>("VariantName")
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)")
                        .HasColumnName("VariantName");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("SongVariant");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SetlistActDo", b =>
                {
                    b.HasOne("Database.Setlists.DataObjects.SetlistDo", "Setlist")
                        .WithMany()
                        .HasForeignKey("SetlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setlist");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SetlistEntryDo", b =>
                {
                    b.HasOne("Database.Setlists.DataObjects.SongMashupDo", "PlayedMashup")
                        .WithMany()
                        .HasForeignKey("PlayedMashupId");

                    b.HasOne("Database.Setlists.DataObjects.SongDo", "PlayedSong")
                        .WithMany()
                        .HasForeignKey("PlayedSongId");

                    b.HasOne("Database.Setlists.DataObjects.SongVariantDo", "PlayedSongVariant")
                        .WithMany()
                        .HasForeignKey("PlayedSongVariantId");

                    b.HasOne("Database.Setlists.DataObjects.SetlistDo", "Setlist")
                        .WithMany("Entries")
                        .HasForeignKey("SetlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Setlists.DataObjects.SetlistActDo", "Act")
                        .WithMany("Entries")
                        .HasForeignKey("SetlistId", "ActNumber");

                    b.Navigation("Act");

                    b.Navigation("PlayedMashup");

                    b.Navigation("PlayedSong");

                    b.Navigation("PlayedSongVariant");

                    b.Navigation("Setlist");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SetlistEntrySongExtraDo", b =>
                {
                    b.HasOne("Database.Setlists.DataObjects.SetlistEntryDo", "SetlistEntry")
                        .WithMany("SongExtras")
                        .HasForeignKey("SetlistEntryId");

                    b.HasOne("Database.Setlists.DataObjects.SongDo", "Song")
                        .WithMany()
                        .HasForeignKey("SongId");

                    b.Navigation("SetlistEntry");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SongDo", b =>
                {
                    b.HasOne("Database.Setlists.DataObjects.AlbumDo", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SongInMashupDo", b =>
                {
                    b.HasOne("Database.Setlists.DataObjects.SongMashupDo", "Mashup")
                        .WithMany("Songs")
                        .HasForeignKey("MashupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Setlists.DataObjects.SongDo", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mashup");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SongVariantDo", b =>
                {
                    b.HasOne("Database.Setlists.DataObjects.SongDo", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SetlistActDo", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SetlistDo", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SetlistEntryDo", b =>
                {
                    b.Navigation("SongExtras");
                });

            modelBuilder.Entity("Database.Setlists.DataObjects.SongMashupDo", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
