name: Run tests

on:
  push:
    branches: [ "*" ]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
    - name: .NET Tests
      # You may pin to the exact commit or the version.
      # uses: EasyDesk/action-dotnet-test@228a60327933ff6200594e89a6fa906a69e5f1e6
      uses: EasyDesk/action-dotnet-test@v1.0.0
      with:
        # The path to the project or solution to test (defaults to the current directory).
        path: LPCalendar.sln
